variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    RUST_BACKTRACE: 1

before_script:
    - rustup component add rustfmt-preview

test:cargo-nightly:
    image: "rustlang/rust:nightly"
    script:
        - rustc --version && cargo --version
        - cargo fmt --all -- --check
        - cargo build  --features serde_support
        - time cargo test --jobs 1
        - cargo bench

test:cargo-stable:
    image: "rust:1.31.1"
    script:
        - rustc --version && cargo --version
        - cargo build  --features serde_support
        - time cargo test --jobs 1
