image: "rust:1.29.0"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    RUST_BACKTRACE: 1

before_script:
    - rustup component add rustfmt-preview

test:cargo:
    script:
        - rustc --version && cargo --version  # Print version info for debugging
        - cargo fmt --all -- --check          # check formatting
        - cargo build                         # don't build w/ serde support because of proc_macro issues with nightly
        - time cargo test --jobs 1            # Run serial for more readable errors

