variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - pedantry
  - clippy
  - test
  - bench

rustfmt:
  stage: pedantry
  image: "rustlang/rust:nightly"
  script:
    # there should be no println in src
    - '[[ `grep -E -r -e "(\s+|^)println" src/*` == "" ]]'
    - rustup component add rustfmt
    - cargo fmt -- --check

cargo-deny:
  stage: pedantry
  image: "rust:1.58"
  script:
    - cargo install --locked cargo-deny
    - cargo deny check

clippy:
  stage: pedantry
  image: "rust:1.58"
  script:
    - rustup component add clippy
    - sed -i 's/\!\[warn/\!\[deny/' src/lib.rs  # deny lints
    - cargo clippy --all-features

test:no-features:
  stage: test
  image: "rust:1.58"
  script:
    - rustc --version && cargo --version
    - cargo test --all

test:feature-arraydist:
  stage: test
  image: "rust:1.58"
  script:
    - rustc --version && cargo --version
    - cargo test --all --features arraydist

test:feature-process:
  stage: test
  image: "rust:1.58"
  script:
    - rustc --version && cargo --version
    - cargo test --all --features process

test:feature-all:
  stage: test
  image: "rust:1.58"
  script:
    - rustc --version && cargo --version
    - cargo test --all --all-features

# just make sure that the benched didn't get broken
bench:cargo-stable:
  stage: bench
  only:
    - master
  image: "rust:1.58"
  script:
    - cargo bench --no-run --features arraydist
