variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - format
  - test
  - bench

format:
  stage: format
  image: "rust:1.46"
  script:
    # there should be no println in src
    - '[[ `grep -E -r -e "(\s+|^)println" src/*` == "" ]]'
    - rustup component add rustfmt
    - cargo fmt -- --check

# # Temporarily disabling due to strange breakages
# test:coverage-nightly:
#   stage: test
#   image: "rustlang/rust:nightly"
#   script:
#     - rustc --version && cargo --version
#     - cargo install cargo-tarpaulin -f
#     - cargo tarpaulin -v -t 240 --features serde1 --run-types Tests Doctests

test:cargo-stable:
  stage: test
  image: "rust:1.47"
  script:
    - rustc --version && cargo --version
    - cargo test --all --all-features

# just make sure that the benched didn't get broken
bench:cargo-stable:
  stage: bench
  only:
    - master
  image: "rust:1.47"
  script:
    - cargo bench --no-run
