variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - format
  - test
  - bench

format:
  stage: format
  image: "rust:1.42"
  script:
    # there should be no println in src
    - '[[ `grep -r "println" src/*` == "" ]]'
    - rustup component add rustfmt
    - cargo fmt -- --check

test:cargo-stable:
  stage: test
  image: "rust:1.45"
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde1
    - time cargo test --jobs 1

test:cargo-nigtly:
  stage: test
  image: "rustlang/rust:nightly"
  # Sometimes nightly breaks, so we have to roll back
  # before_script:
  #   - rustup install nightly-2020-03-11 --no-self-update
  #   - rustup override set nightly-2020-03-11
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde1
    - time cargo test --jobs 1

bench:cargo-stable:
  stage: bench
  only:
    - master
  image: "rust:1.45"
  script:
    - cargo bench --no-run
