image: "rustlang/rust:nightly"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    RUST_BACKTRACE: 1

before_script:
    - rustup component add rustfmt-preview

test:cargo:
    script:
        - rustc --version && cargo --version
        - cargo fmt --all -- --check
        - cargo build  --features serde_support
        - time cargo test --jobs 1

