variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - test
  - bench

test:cargo-stable:
  stage: test
  image: "rust:1.40.0"
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde_support
    - time cargo test --jobs 1

test:cargo-nigtly:
  stage: test
  image: "rustlang/rust:nightly"
  before_script:
    - rustup install nightly-2019-12-19 --no-self-update
    - rustup override set nightly-2019-12-19
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde_support
    - time cargo test --jobs 1

bench:cargo-stable:
  stage: bench
  image: "rust:1.40.0"
  script:
    - cargo bench --no-run
