variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - test
  - bench

test:cargo-stable:
  stage: test
  image: "rust:1.41"
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde1
    - time cargo test --jobs 1

test:cargo-nigtly:
  stage: test
  image: "rustlang/rust:nightly"
  # Sometimes nightly breaks, so we have to roll back
  before_script:
    - rustup install nightly-2020-02-06 --no-self-update
    - rustup override set nightly-2020-02-06
  script:
    - rustc --version && cargo --version
    - cargo build  --features serde1
    - time cargo test --jobs 1

bench:cargo-stable:
  stage: bench
  image: "rust:1.41"
  script:
    - cargo bench --no-run
