[package]
name = "rv"
version = "0.11.0-beta.3"
authors = ["Baxter Eaves", "Michael Schmidt"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]
edition = "2018"
include = ["README.md", "src/**/*", "benches/*", "Cargo.toml"]

[features]
serde1 = ["serde", "nalgebra/serde-serialize"]
process = ["serde", "nalgebra/serde-serialize", "argmin"]

[badges]
gitlab = { repository = "baxe/rv", tag = "v0.11.0-beta.3" }
maintenance = { status = "actively-developed" }

[dependencies]
argmin = { version = "0.3", optional = true }
doc-comment = "0.3"
log = "0.4"
lru = "0.6"
nalgebra = "0.22"
num = "0.3"
once_cell = "1"
rand = { version = "0.7", features = ["small_rng"] }
rand_distr = "0.2"
serde = {version = "1", features = ["derive"], optional = true}
special = "0.8"

[dev-dependencies]
assert = "0.7"
criterion = "0.3"
indoc = "1"
serde_yaml = "0.8"


# Benchmarks
# ==========
[[bench]]
name = "mvg"
harness = false

[[bench]]
name = "gev"
harness = false

[[bench]]
name = "wishart"
harness = false

[[bench]]
name = "categorical"
harness = false

[[bench]]
name = "beta"
harness = false

[[bench]]
name = "quad"
harness = false

[[bench]]
name = "rv"
harness = false
