[package]
name = "rv"
version = "0.2.3"
authors = ["Baxter Eaves"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]

[features]
serde_support = ["serde", "serde_derive"]

[badges]
gitlab = { repository = "baxe/rv", branch = "master" }

[dependencies]
num = "0.2.0"
rand = "0.5.3"
special = "0.7.8"
nalgebra = {version = "0.16.0", features = ["serde-serialize"]}

serde = {version = "1.0.70", optional = true}
serde_derive = {version = "1.0.70", optional = true}

[dev-dependencies]
assert = "0.7.4"
