[package]
name = "rv"
version = "0.13.2"
authors = ["Baxter Eaves", "Michael Schmidt"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]
edition = "2018"
include = ["README.md", "src/**/*", "benches/*", "Cargo.toml"]

[badges]
gitlab = { repository = "baxe/rv", tag = "v0.13.1" }
maintenance = { status = "actively-developed" }

[dependencies]
argmin = { version = "0.4.5", optional = true }
doc-comment = "0.3"
lru = "0.8.1"
nalgebra = { version = "0.27", optional = true }
num = "0.3"
once_cell = "1.15"
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"
serde = {version = "1", features = ["derive"], optional = true}
special = "0.8"
peroxide = "0.30"

[dev-dependencies]
assert = "0.7"
criterion = "0.3"
indoc = "1"
serde_yaml = "0.8"
approx = "0.5"
rand_xoshiro = "0.6"

[features]
serde1 = ["serde", "nalgebra/serde-serialize"]
arraydist = ["nalgebra"]
process = ["serde", "nalgebra/serde-serialize", "argmin", "arraydist"]


# Benchmarks
# ==========
[[bench]]
name = "mvg"
harness = false

[[bench]]
name = "gev"
harness = false

[[bench]]
name = "wishart"
harness = false

[[bench]]
name = "categorical"
harness = false

[[bench]]
name = "beta"
harness = false

[[bench]]
name = "quad"
harness = false

[[bench]]
name = "rv"
harness = false

[[bench]]
name = "mixture_entropy"
harness = false
