[package]
name = "rv"
version = "0.1.0"
authors = ["Baxter Eaves"]
description = "Random variables"
readme = "README.md"
license = "MIT"
license-file = "LICENSE.txt"

[badges]
gitlab = { repository = "baxe/rv", branch = "master" }

[dependencies]
rand = "*"
assert = "*"
serde = "*"
serde_derive = "*"
special = { git = "https://github.com/BaxterEaves/special" }
