[package]
name = "rv"
version = "0.8.0-beta.1"
authors = ["Baxter Eaves", "Michael Schmidt"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]
edition = "2018"

[features]
serde_support = ["serde", "serde_derive", "nalgebra/serde-serialize"]

[badges]
gitlab = { repository = "baxe/rv", tag = "v0.8.0-beta.1" }
maintenance = { status = "actively-developed" }

[dependencies]
num = "0.2"
rand = "0.7"
special = "0.8"
nalgebra = "0.18"
quadrature = "0.1"
doc-comment = "0.3"
getset = "0.0.7"
rand_distr = "0.2"
once_cell = "1.2"

serde = {version = "1", optional = true}
serde_derive = {version = "1", optional = true}

[dev-dependencies]
assert = "0.7"
criterion = "0.2"
indoc = "0.3"
serde_yaml = "0.8"


# Benchmarks
# ==========
[[bench]]
name = "mvg"
harness = false

[[bench]]
name = "gev"
harness = false

[[bench]]
name = "wishart"
harness = false

[[bench]]
name = "categorical"
harness = false

[[bench]]
name = "beta"
harness = false
