[package]
name = "rv"
version = "0.5.0"
authors = ["Baxter Eaves", "Michael Schmidt"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]
edition = "2018"

[features]
serde_support = ["serde", "serde_derive", "nalgebra/serde-serialize"]

[badges]
gitlab = { repository = "baxe/rv", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
num = "0.2.0"
rand = "0.5.5"
special = "0.7.8"
nalgebra = "0.16.1"
quadrature = "0.1.2"
doc-comment = "0.3.1"

serde = {version = "1.0.70", optional = true}
serde_derive = {version = "1.0.70", optional = true}

[dev-dependencies]
assert = "0.7.4"
