[package]
name = "rv"
version = "0.10.4"
authors = ["Baxter Eaves", "Michael Schmidt"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]
edition = "2018"

[features]
serde1 = ["serde_derive", "nalgebra/serde-serialize"]

[badges]
gitlab = { repository = "baxe/rv", tag = "v0.10.3" }
maintenance = { status = "actively-developed" }

[dependencies]
num = "0.3"
rand = "0.7"
special = "0.8"
nalgebra = "0.22"
doc-comment = "0.3"
rand_distr = "0.2"
once_cell = "1"
lru = "0.4"
argmin = "0.3"

serde = {version = "1", features=["derive"]}
serde_derive = {version = "1", optional = true}

[dev-dependencies]
assert = "0.7"
criterion = "0.3"
indoc = "1"
serde_yaml = "0.8"
approx = "0.3"


# Benchmarks
# ==========
[[bench]]
name = "mvg"
harness = false

[[bench]]
name = "gev"
harness = false

[[bench]]
name = "wishart"
harness = false

[[bench]]
name = "categorical"
harness = false

[[bench]]
name = "beta"
harness = false

[[bench]]
name = "quad"
harness = false

[[bench]]
name = "rv"
harness = false
