[package]
name = "rv"
version = "0.2.0"
authors = ["Baxter Eaves"]
description = "Random variables"
repository = "https://gitlab.com/baxe/rv"
readme = "README.md"
license = "MIT"
keywords = ["Probability", "Statistics", "Bayesian", "Machine-learning"]
categories = ["science"]

[badges]
gitlab = { repository = "https://gitlab.com/baxe/rv", branch = "master" }

[dependencies]
num = "0.2.0"
rand = "0.5.3"
serde = "1.0.70"
serde_derive = "1.0.70"
special = "0.7.8"

[dev-dependencies]
assert = "0.7.4"
